version: '3.7'
services:
  scrape:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    networks:
      dm-server_db-network:
      duckguessr_duckguessr-network:
    command: 'sh -c "[ -z \"$$DATASET\" ] && echo \"No dataset provided\" && exit 1 || npm install && npm rebuild mmmagic && node scrape.js \"$$DATASET\""'

  pack:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    networks:
      dm-server_db-network:
      duckguessr_duckguessr-network:
    command: 'sh -c "[ -z \"$$DATASET\" ] && echo \"No dataset provided\" && exit 1 || npm install && npm rebuild mmmagic && node pack.js \"$$DATASET\""'

  download-model:
    image: python:3.8
    working_dir: /app
    environment:
      PATH: '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin'
    volumes:
      - ./input:/app/input
    command: >
      sh -c "
        [ -z \"$$DATASET\" ] && echo \"No dataset provided\" && exit 1 \
        || pip install --user kaggle \
        && kaggle kernels output $$KAGGLE_USERNAME/predict-duck-artist-$$DATASET -p input/$$DATASET \
        && kaggle datasets download --unzip $$KAGGLE_USERNAME/inducks-drawings-by-artist-$$DATASET-md -p input/$$DATASET \
      "

  predict-server:
    image: python:3.8
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always
    networks:
      - public-network
    command: 'sh -c "pip install -r requirements.txt && python3 predict_server.py"'

networks:
  public-network:
    external: true
  dm-server_db-network:
    external: true
  duckguessr_duckguessr-network:
    external: true